export async function main(ns) {
    let targets = [
        // "foodnstuff",
        "sigma-cosmetics",
        "joesguns",
        "nectar-net",
        "hong-fang-tea",
        "harakiri-sushi",
        "neo-net",
        "zer0",
        "max-hardware",
        "iron-gym",
        "phantasy",
        "silver-helix",
        "omega-net",
        "crush-fitness",
        "johnson-ortho",
        "the-hub",
        "comptek",
        "netlink",
        "rothman-uni",
        "catalyst",
        "summit-uni",
        "rho-construction",
        "millenium-fitness",
        "aevum-police",
        "alpha-ent",
        "syscore",
        "lexo-corp",
        "snap-fitness",
        "global-pharm",
        "applied-energetics",
        "unitalife",
        "univ-energy",
        "nova-med",
        "zb-def",
        "zb-institute",
        "vitalife",
        "titan-labs",
        "solaris",
        "microdyne",
        "helios",
        "deltaone",
        "icarus",
        "omnia",
        "defcomm",
        "galactic-cyber",
        "infocomm",
        "taiyang-digital",
        "stormtech",
        "aerocorp",
        "clarkinc",
        "omnitek",
        "nwo",
        "4sigma",
        "blade",
        "b-and-a",
        "ecorp",
        "fulcrumtech",
        "megacorp",
        "kuai-gong",
        // "fulcrumassets",
        "powerhouse-fitness"
    ];
    let taking = ns.args.length > 0 ? ns.args[0] : '';
    for(let i = 0; i < targets.length; i++)
        await ns.run('calculator.js', 1, targets[i] + (taking ? `;${taking}` : ''));
}